export interface CatBreed {
  value: string; // slug stored on the Video
  label: string; // Japanese display name
}

export interface CatBreedGroup {
  group: string;
  breeds: CatBreed[];
}

// Grouped, comprehensive cat list: recognized domestic breeds (TICA / CFA /
// FIFe / WCF + well-known experimental breeds) plus the wild Felidae species.
export const CAT_BREED_GROUPS: CatBreedGroup[] = [
  {
    group: "家猫の品種",
    breeds: [
      { value: "mixed", label: "雑種（ミックス）" },
      { value: "abyssinian", label: "アビシニアン" },
      { value: "aegean", label: "エーゲキャット" },
      { value: "american_bobtail", label: "アメリカンボブテイル" },
      { value: "american_curl", label: "アメリカンカール" },
      { value: "american_shorthair", label: "アメリカンショートヘア" },
      { value: "american_wirehair", label: "アメリカンワイヤーヘア" },
      { value: "arabian_mau", label: "アラビアンマウ" },
      { value: "asian", label: "アジアン" },
      { value: "australian_mist", label: "オーストラリアンミスト" },
      { value: "balinese", label: "バリニーズ" },
      { value: "bambino", label: "バンビーノ" },
      { value: "bengal", label: "ベンガル" },
      { value: "birman", label: "バーマン" },
      { value: "bombay", label: "ボンベイ" },
      { value: "brazilian_shorthair", label: "ブラジリアンショートヘア" },
      { value: "british_longhair", label: "ブリティッシュロングヘア" },
      { value: "british_shorthair", label: "ブリティッシュショートヘア" },
      { value: "burmese", label: "バーミーズ" },
      { value: "burmilla", label: "バーミラ" },
      { value: "california_spangled", label: "カリフォルニアスパングルド" },
      { value: "chantilly_tiffany", label: "シャンティリー・ティファニー" },
      { value: "chartreux", label: "シャルトリュー" },
      { value: "chausie", label: "チャウシー" },
      { value: "cheetoh", label: "チートー" },
      { value: "colorpoint_shorthair", label: "カラーポイントショートヘア" },
      { value: "cornish_rex", label: "コーニッシュレックス" },
      { value: "cymric", label: "サイミック" },
      { value: "cyprus", label: "キプロスキャット" },
      { value: "devon_rex", label: "デボンレックス" },
      { value: "donskoy", label: "ドンスコイ" },
      { value: "dragon_li", label: "ドラゴンリー（中国狸花猫）" },
      { value: "egyptian_mau", label: "エジプシャンマウ" },
      { value: "european_shorthair", label: "ヨーロピアンショートヘア" },
      { value: "exotic_shorthair", label: "エキゾチックショートヘア" },
      { value: "foldex", label: "フォーレックス" },
      { value: "german_rex", label: "ジャーマンレックス" },
      { value: "havana_brown", label: "ハバナブラウン" },
      { value: "highlander", label: "ハイランダー" },
      { value: "himalayan", label: "ヒマラヤン" },
      { value: "japanese_bobtail", label: "ジャパニーズボブテイル" },
      { value: "javanese", label: "ジャバニーズ" },
      { value: "kanaani", label: "カナアニ" },
      { value: "khao_manee", label: "カオマニー" },
      { value: "korat", label: "コラット" },
      { value: "korn_ja", label: "コーンジャ" },
      { value: "kurilian_bobtail", label: "クリリアンボブテイル" },
      { value: "laperm", label: "ラパーマ" },
      { value: "lykoi", label: "ライコイ" },
      { value: "maine_coon", label: "メインクーン" },
      { value: "manx", label: "マンクス" },
      { value: "mekong_bobtail", label: "メコンボブテイル" },
      { value: "minskin", label: "ミンスキン" },
      { value: "munchkin", label: "マンチカン" },
      { value: "nebelung", label: "ネベロング" },
      {
        value: "norwegian_forest",
        label: "ノルウェージャンフォレストキャット",
      },
      { value: "ocicat", label: "オシキャット" },
      { value: "oriental_longhair", label: "オリエンタルロングヘア" },
      { value: "oriental_shorthair", label: "オリエンタルショートヘア" },
      { value: "persian", label: "ペルシャ" },
      { value: "peterbald", label: "ピーターボールド" },
      { value: "pixie_bob", label: "ピクシーボブ" },
      { value: "ragamuffin", label: "ラガマフィン" },
      { value: "ragdoll", label: "ラグドール" },
      { value: "russian_blue", label: "ロシアンブルー" },
      { value: "savannah", label: "サバンナ" },
      { value: "scottish_fold", label: "スコティッシュフォールド" },
      { value: "selkirk_rex", label: "セルカークレックス" },
      { value: "serengeti", label: "セレンゲティ" },
      { value: "siamese", label: "シャム" },
      { value: "siberian", label: "サイベリアン" },
      { value: "singapura", label: "シンガプーラ" },
      { value: "snowshoe", label: "スノーシュー" },
      { value: "sokoke", label: "ソコケ" },
      { value: "somali", label: "ソマリ" },
      { value: "sphynx", label: "スフィンクス" },
      { value: "suphalak", label: "スファラック" },
      { value: "thai", label: "タイ" },
      { value: "tonkinese", label: "トンキニーズ" },
      { value: "toyger", label: "トイガー" },
      { value: "turkish_angora", label: "ターキッシュアンゴラ" },
      { value: "turkish_van", label: "ターキッシュバン" },
      { value: "ukrainian_levkoy", label: "ウクライナンレフコイ" },
      { value: "york_chocolate", label: "ヨークチョコレート" },
    ],
  },
  {
    group: "野生のネコ科",
    breeds: [
      { value: "lion", label: "ライオン" },
      { value: "tiger", label: "トラ" },
      { value: "leopard", label: "ヒョウ" },
      { value: "jaguar", label: "ジャガー" },
      { value: "snow_leopard", label: "ユキヒョウ" },
      { value: "clouded_leopard", label: "ウンピョウ" },
      { value: "sunda_clouded_leopard", label: "スンダウンピョウ" },
      { value: "cheetah", label: "チーター" },
      { value: "cougar", label: "ピューマ（クーガー）" },
      { value: "eurasian_lynx", label: "ユーラシアオオヤマネコ" },
      { value: "canada_lynx", label: "カナダオオヤマネコ" },
      { value: "iberian_lynx", label: "スペインオオヤマネコ" },
      { value: "bobcat", label: "ボブキャット" },
      { value: "ocelot", label: "オセロット" },
      { value: "margay", label: "マーゲイ" },
      { value: "serval", label: "サーバル" },
      { value: "caracal", label: "カラカル" },
      { value: "european_wildcat", label: "ヨーロッパヤマネコ" },
      { value: "african_wildcat", label: "リビアヤマネコ" },
      { value: "chinese_mountain_cat", label: "ハイイロネコ（中国山猫）" },
      { value: "jungle_cat", label: "ジャングルキャット" },
      { value: "sand_cat", label: "スナネコ" },
      { value: "black_footed_cat", label: "クロアシネコ" },
      { value: "pallas_cat", label: "マヌルネコ" },
      { value: "fishing_cat", label: "スナドリネコ" },
      { value: "leopard_cat", label: "ベンガルヤマネコ" },
      { value: "iriomote_cat", label: "イリオモテヤマネコ" },
      { value: "tsushima_cat", label: "ツシマヤマネコ" },
      { value: "rusty_spotted_cat", label: "サビイロネコ" },
      { value: "flat_headed_cat", label: "マレーヤマネコ" },
      { value: "marbled_cat", label: "マーブルキャット" },
      { value: "asian_golden_cat", label: "アジアゴールデンキャット" },
      { value: "african_golden_cat", label: "アフリカゴールデンキャット" },
      { value: "bay_cat", label: "ボルネオヤマネコ" },
      { value: "geoffroys_cat", label: "ジョフロイネコ" },
      { value: "kodkod", label: "コドコド" },
      { value: "oncilla", label: "オンシラ（タイガーキャット）" },
      { value: "pampas_cat", label: "パンパスキャット" },
      { value: "andean_mountain_cat", label: "アンデスネコ" },
      { value: "jaguarundi", label: "ジャガランディ" },
    ],
  },
  {
    group: "その他",
    breeds: [{ value: "other", label: "その他・不明" }],
  },
];

// Flat list (used by callers that just need every option).
export const CAT_BREEDS: CatBreed[] = CAT_BREED_GROUPS.flatMap((g) => g.breeds);

const LABELS: Record<string, string> = Object.fromEntries(
  CAT_BREEDS.map((b) => [b.value, b.label]),
);

/** Japanese label for a breed slug; falls back to the raw value. */
export function breedLabel(value: string): string {
  return LABELS[value] ?? value;
}
